default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # added setting
  host: db
  username: root
  password: password

development:
  <<: *default
  database: sado_bc_development

test:
  <<: *default
  database: sado_bc_test

production:
  <<: *default
  database: sado_bc_production
  # username: app
  # password: <%= ENV['APP_DATABASE_PASSWORD'] %>